spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/GoodluckBuddy
    username: root
    password: ${DB_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "http://3.106.57.171/login/oauth2/code/google"
            scope:
              - email
              - profile

          kakao:
            client-id: ${KAKAO_REST_KEY}
            client-secret: ${KAKAO_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "http://3.106.57.171/login/oauth2/code/kakao"
            client-name: Kakao
            scope: [ ]
            client-authentication-method: client_secret_post

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  token:
    secretKey: ${JWT_TOKEN_SECRETKEY}
    expiration:
      access: 1800000

server:
  port: 8080
  address: 0.0.0.0
