name: GoodluckBuddy Dev CI/CD

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3  # 저장소 코드 체크아웃

      - name: Set up JDK 21  # Java 개발 킷 설정
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Make application.yaml  # application.yaml 파일 생성
        run: |
          cd ./src/main/resources
          echo "${{ secrets.APPLICATION_YAML }}" > ./application.yaml
        shell: bash

      - name: Grant execute permission for gradlew  # gradlew 실행 권한 부여
        run: chmod +x gradlew

      - name: Build with Gradle  # Gradle을 사용하여 프로젝트 빌드
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Upload build artifact  # 빌드된 아티팩트 업로드
        uses: actions/upload-artifact@v4
        with:
          name: GoodluckBuddy_server
          path: build/libs/*.jar

  deploy:
    needs: build  # build 작업이 성공적으로 완료된 후 실행
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact  # 이전 단계에서 업로드한 아티팩트 다운로드
        uses: actions/download-artifact@v4
        with:
          name: GoodluckBuddy_server
          path: build/libs/

      - name: Deploy to EC2  # EC2에 배포
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          JWT_TOKEN_SECRETKEY: ${{ secrets.JWT_TOKEN_SECRETKEY }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          KAKAO_REST_KEY: ${{ secrets.KAKAO_REST_KEY }}
          KAKAO_CLIENT_SECRET: ${{ secrets.KAKAO_CLIENT_SECRET }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          echo "$EC2_SSH_KEY" | base64 -d > glbd.pem
          chmod 600 glbd.pem
          jar_file=$(find build/libs -name '*.jar' ! -name '*plain.jar' | head -n 1)
          scp -i glbd.pem -o StrictHostKeyChecking=no "$jar_file" $EC2_USERNAME@$EC2_HOST:/home/$EC2_USERNAME/umc7thServer.jar
          ssh -i glbd.pem -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_HOST "
          pgrep java | xargs -r kill -15  # 기존 Java 프로세스 종료
          sleep 10
          # 환경변수 함께 전달 후 애플리케이션 실행
          export DB_PASSWORD='$DB_PASSWORD'
          export SECRET_KEY='$JWT_TOKEN_SECRETKEY'
          export GOOGLE_CLIENT_ID='$GOOGLE_CLIENT_ID'
          export GOOGLE_CLIENT_SECRET='$GOOGLE_CLIENT_SECRET'
          export KAKAO_REST_KEY='$KAKAO_REST_KEY'
          export KAKAO_CLIENT_SECRET='$KAKAO_CLIENT_SECRET'
          nohup java -jar /home/$EC2_USERNAME/umc7thServer.jar > app.log 2>&1 &
          "
